"""add motivation system tables

Revision ID: 20250120000000
Revises: 7736e15a8b7b
Create Date: 2025-01-20 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20250120000000'
down_revision: Union[str, Sequence[str], None] = '7736e15a8b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create motivation_states table
    op.create_table('motivation_states',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('boredom', sa.Float(), nullable=False),
        sa.Column('curiosity', sa.Float(), nullable=False),
        sa.Column('tiredness', sa.Float(), nullable=False),
        sa.Column('satisfaction', sa.Float(), nullable=False),
        sa.Column('last_tick', sa.Float(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_motivation_states_active', 'motivation_states', ['is_active'], unique=False)
    
    # Create topic_scores table
    op.create_table('topic_scores',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('topic_name', sa.String(length=255), nullable=False),
        sa.Column('motivation_score', sa.Float(), nullable=False),
        sa.Column('engagement_score', sa.Float(), nullable=False),
        sa.Column('success_rate', sa.Float(), nullable=False),
        sa.Column('staleness_pressure', sa.Float(), nullable=False),
        sa.Column('last_researched', sa.Float(), nullable=True),
        sa.Column('staleness_coefficient', sa.Float(), nullable=False),
        sa.Column('is_active_research', sa.Boolean(), nullable=False),
        sa.Column('total_findings', sa.Integer(), nullable=False),
        sa.Column('read_findings', sa.Integer(), nullable=False),
        sa.Column('bookmarked_findings', sa.Integer(), nullable=False),
        sa.Column('integrated_findings', sa.Integer(), nullable=False),
        sa.Column('average_quality', sa.Float(), nullable=True),
        sa.Column('last_quality_update', sa.Float(), nullable=True),
        sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'topic_name', name='uq_topic_score_user_topic')
    )
    op.create_index('ix_topic_scores_user_active', 'topic_scores', ['user_id', 'is_active_research'], unique=False)
    op.create_index('ix_topic_scores_motivation', 'topic_scores', ['motivation_score'], unique=False)
    op.create_index('ix_topic_scores_last_researched', 'topic_scores', ['last_researched'], unique=False)
    
    # Create motivation_configs table
    op.create_table('motivation_configs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('boredom_rate', sa.Float(), nullable=False),
        sa.Column('curiosity_decay', sa.Float(), nullable=False),
        sa.Column('tiredness_decay', sa.Float(), nullable=False),
        sa.Column('satisfaction_decay', sa.Float(), nullable=False),
        sa.Column('global_threshold', sa.Float(), nullable=False),
        sa.Column('topic_threshold', sa.Float(), nullable=False),
        sa.Column('engagement_weight', sa.Float(), nullable=False),
        sa.Column('quality_weight', sa.Float(), nullable=False),
        sa.Column('staleness_scale', sa.Float(), nullable=False),
        sa.Column('check_interval', sa.Integer(), nullable=False),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_motivation_configs_default', 'motivation_configs', ['is_default'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_motivation_configs_default', table_name='motivation_configs')
    op.drop_table('motivation_configs')
    op.drop_index('ix_topic_scores_last_researched', table_name='topic_scores')
    op.drop_index('ix_topic_scores_motivation', table_name='topic_scores')
    op.drop_index('ix_topic_scores_user_active', table_name='topic_scores')
    op.drop_table('topic_scores')
    op.drop_index('ix_motivation_states_active', table_name='motivation_states')
    op.drop_table('motivation_states')
    # ### end Alembic commands ###


