"""create user profiles

Revision ID: 1a695f13d7a0
Revises: 20251028110000
Create Date: 2025-11-13 15:02:37.888516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a695f13d7a0'
down_revision: Union[str, Sequence[str], None] = '20251028110000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('personality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('engagement_analytics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personalization_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_identities_user_id', 'identities', ['user_id'], unique=False)
    op.create_unique_constraint('uq_identity_user_provider', 'identities', ['user_id', 'provider'])
    op.drop_column('users', 'additional_traits')
    op.drop_column('users', 'meta_data')
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('additional_traits', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('uq_identity_user_provider', 'identities', type_='unique')
    op.drop_index('ix_identities_user_id', table_name='identities')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
