"""update research findings table

Revision ID: 64dcb4c7f0d9
Revises: 6d0a9535d098
Create Date: 2025-12-16 10:07:29.301146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64dcb4c7f0d9'
down_revision: Union[str, Sequence[str], None] = '6d0a9535d098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_findings', sa.Column('findings_content', sa.Text(), nullable=True))
    op.add_column('research_findings', sa.Column('formatted_content', sa.Text(), nullable=True))
    op.add_column('research_findings', sa.Column('research_query', sa.Text(), nullable=True))
    op.add_column('research_findings', sa.Column('findings_summary', sa.Text(), nullable=True))
    op.add_column('research_findings', sa.Column('source_urls', postgresql.ARRAY(sa.TEXT()), nullable=True))
    op.add_column('research_findings', sa.Column('citations', postgresql.ARRAY(sa.TEXT()), nullable=True))
    op.add_column('research_findings', sa.Column('key_insights', postgresql.ARRAY(sa.TEXT()), nullable=True))
    op.add_column('research_findings', sa.Column('search_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_findings_time'), table_name='research_findings')
    op.drop_index(op.f('ix_findings_user_topic'), table_name='research_findings')
    op.drop_constraint(op.f('uq_research_finding_user_finding'), 'research_findings', type_='unique')
    op.drop_column('research_findings', 'research_time')
    # ### end Alembic commands ###

    op.execute("""
    CREATE OR REPLACE FUNCTION update_topic_stats_on_finding_insert() RETURNS trigger AS $$
    BEGIN
      UPDATE research_topics
      SET
        research_count  = research_count + 1,
        last_researched = NEW.created_at
      WHERE id = NEW.topic_id;
      RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    DROP TRIGGER IF EXISTS trg_rf_after_insert ON research_findings;
    CREATE TRIGGER trg_rf_after_insert
    AFTER INSERT ON research_findings
    FOR EACH ROW
    EXECUTE FUNCTION update_topic_stats_on_finding_insert();
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_rf_after_insert ON research_findings;")
    op.execute("DROP FUNCTION IF EXISTS update_topic_stats_on_finding_insert();")

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_findings', sa.Column('research_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_research_finding_user_finding'), 'research_findings', ['user_id', 'finding_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_findings_user_topic'), 'research_findings', ['user_id', 'topic_name'], unique=False)
    op.create_index(op.f('ix_findings_time'), 'research_findings', ['research_time'], unique=False)
    op.drop_column('research_findings', 'search_sources')
    op.drop_column('research_findings', 'key_insights')
    op.drop_column('research_findings', 'citations')
    op.drop_column('research_findings', 'source_urls')
    op.drop_column('research_findings', 'findings_summary')
    op.drop_column('research_findings', 'research_query')
    op.drop_column('research_findings', 'formatted_content')
    op.drop_column('research_findings', 'findings_content')
    # ### end Alembic commands ###
