"""change research topics

Revision ID: 6d0a9535d098
Revises: 0f2f604b87bc
Create Date: 2025-12-11 10:08:51.903958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d0a9535d098'
down_revision: Union[str, Sequence[str], None] = '0f2f604b87bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('research_topics', 'name',
               existing_type=sa.TEXT(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    
    # Clean up duplicates before creating unique constraint
    # Keep the most recent topic for each (user_id, name) pair
    op.execute("""
        DELETE FROM research_topics
        WHERE id NOT IN (
            SELECT DISTINCT ON (user_id, LOWER(name))
                id
            FROM research_topics
            ORDER BY user_id, LOWER(name), created_at DESC
        )
    """)
    
    op.create_unique_constraint('uq_research_topics_user_name', 'research_topics', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_research_topics_user_name', 'research_topics', type_='unique')
    op.alter_column('research_topics', 'name',
               existing_type=postgresql.CITEXT(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
