"""add topic id for topic scores and research findings

Revision ID: 0f2f604b87bc
Revises: a8916f2612a3
Create Date: 2025-12-08 10:28:08.458153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f2f604b87bc'
down_revision: Union[str, Sequence[str], None] = 'a8916f2612a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_findings', sa.Column('topic_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_research_findings_topic_id'), 'research_findings', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'research_findings', 'research_topics', ['topic_id'], ['id'], ondelete='CASCADE')
    op.add_column('topic_scores', sa.Column('topic_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_topic_scores_topic_id'), 'topic_scores', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'topic_scores', 'research_topics', ['topic_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_scores', type_='foreignkey')
    op.drop_index(op.f('ix_topic_scores_topic_id'), table_name='topic_scores')
    op.drop_column('topic_scores', 'topic_id')
    op.drop_constraint(None, 'research_findings', type_='foreignkey')
    op.drop_index(op.f('ix_research_findings_topic_id'), table_name='research_findings')
    op.drop_column('research_findings', 'topic_id')
    # ### end Alembic commands ###
